stages:
  - env_check
  - deploy

check_folder:
  stage: env_check
  script: # variable?
    - mkdir /var/www/dict-back

deploy-job:      
  stage: deploy
  script:
    - dotnet restore
    - dotnet publish --configuration Release --no-restore --a linux-x64 --nologo -o /var/www/dict-back
