variables: 
  DEPLOYMENT_FOLDER: '/var/www/dict-back'


stages:
  - env-check
  - deploy
  - start-app

check-folder-job:
  stage: env-check
  script:
    - mkdir -p $DEPLOYMENT_FOLDER

deploy-job:      
  stage: deploy
  script:
    - dotnet restore
    - dotnet publish DictionaryBack.API/DictionaryBack.API.csproj --configuration Release --no-restore --nologo -o $DEPLOYMENT_FOLDER
    - chmod 777 $DEPLOYMENT_FOLDER/DictionaryBack.API.dll

start-app-job:
  stage: start-app
  script:
    - cd $DEPLOYMENT_FOLDER
    - dotnet DictionaryBack.API.dll --urls "http://localhost:61987"


