stages:          
  - build
  - test
  - deploy

build-job:       
  stage: build
  script:
    - dotnet restore
    - dotnet build --configuration Release --no-restore

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 60 seconds."

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application..."
