// <auto-generated />
using DictionaryBack.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DictionaryBack.DAL.Migrations
{
    [DbContext(typeof(DictionaryContext))]
    partial class DictionaryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("DictionaryBack.Domain.Translation", b =>
                {
                    b.Property<string>("TermId")
                        .HasColumnType("text");

                    b.Property<string>("Meaning")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("meaning");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("WordTerm")
                        .HasColumnType("character varying(200)");

                    b.HasKey("TermId", "Meaning");

                    b.HasIndex("WordTerm");

                    b.ToTable("translations");
                });

            modelBuilder.Entity("DictionaryBack.Domain.Word", b =>
                {
                    b.Property<string>("Term")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("term");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Topic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("user")
                        .HasColumnName("topic");

                    b.HasKey("Term");

                    b.ToTable("words");
                });

            modelBuilder.Entity("DictionaryBack.Domain.Translation", b =>
                {
                    b.HasOne("DictionaryBack.Domain.Word", null)
                        .WithMany("Translations")
                        .HasForeignKey("WordTerm");
                });

            modelBuilder.Entity("DictionaryBack.Domain.Word", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
